/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Grupo2;

/**
 *
 * @author Daniel Bravo
 */
public class Vis_evaluacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vis_evaluacion
     */
    public Vis_evaluacion() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_lienzoPrincipal = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jp_contenedorGrupo = new javax.swing.JPanel();
        jb_fecha = new javax.swing.JLabel();
        jb_calibracion = new javax.swing.JLabel();
        jb_vapor = new javax.swing.JLabel();
        jb_transporte = new javax.swing.JLabel();
        txt_calibracion = new javax.swing.JTextField();
        txt_vapor = new javax.swing.JTextField();
        txt_transporte = new javax.swing.JTextField();
        jb_semana = new javax.swing.JLabel();
        jcomb_semana = new javax.swing.JComboBox<>();
        jb_lDedos = new javax.swing.JLabel();
        txt_dedos = new javax.swing.JTextField();
        jb_pedidos = new javax.swing.JLabel();
        txt_pedidos = new javax.swing.JTextField();
        jb_tipoCaja = new javax.swing.JLabel();
        txt_tipoCaja = new javax.swing.JTextField();
        jb_finca = new javax.swing.JLabel();
        jb_destino = new javax.swing.JLabel();
        jb_codigo = new javax.swing.JLabel();
        jb_fumigacion = new javax.swing.JLabel();
        jb_destino2 = new javax.swing.JLabel();
        txt_fumigacion = new javax.swing.JTextField();
        txt_destino2 = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_destino1 = new javax.swing.JTextField();
        jcom_finca = new javax.swing.JComboBox<>();
        redondeado2 = new Recursos_Codigo.Redondeado();
        jb_btn_siguiente = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(965, 605));
        setMinimumSize(new java.awt.Dimension(965, 605));
        setPreferredSize(new java.awt.Dimension(965, 605));

        jp_lienzoPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedorGrupo.setBackground(new java.awt.Color(255, 255, 255));

        jb_fecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fecha.setForeground(new java.awt.Color(0, 0, 0));
        jb_fecha.setText("FECHA:");

        jb_calibracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_calibracion.setForeground(new java.awt.Color(0, 0, 0));
        jb_calibracion.setText("CALIBRACION:");

        jb_vapor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_vapor.setForeground(new java.awt.Color(0, 0, 0));
        jb_vapor.setText("VAPOR:");

        jb_transporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_transporte.setForeground(new java.awt.Color(0, 0, 0));
        jb_transporte.setText("TRANSPORTE:");

        txt_calibracion.setBackground(new java.awt.Color(255, 255, 255));
        txt_calibracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_calibracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calibracionActionPerformed(evt);
            }
        });

        txt_vapor.setBackground(new java.awt.Color(255, 255, 255));
        txt_vapor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_transporte.setBackground(new java.awt.Color(255, 255, 255));
        txt_transporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_semana.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_semana.setForeground(new java.awt.Color(0, 0, 0));
        jb_semana.setText("SEMANA:");

        jcomb_semana.setBackground(new java.awt.Color(255, 255, 255));
        jcomb_semana.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcomb_semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanas" }));

        jb_lDedos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_lDedos.setForeground(new java.awt.Color(0, 0, 0));
        jb_lDedos.setText("L. DEDOS:");

        txt_dedos.setBackground(new java.awt.Color(255, 255, 255));
        txt_dedos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_pedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_pedidos.setForeground(new java.awt.Color(0, 0, 0));
        jb_pedidos.setText("PEDIDO:");

        txt_pedidos.setBackground(new java.awt.Color(255, 255, 255));
        txt_pedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_tipoCaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_tipoCaja.setForeground(new java.awt.Color(0, 0, 0));
        jb_tipoCaja.setText("TIPO DE CAJA:");

        txt_tipoCaja.setBackground(new java.awt.Color(255, 255, 255));
        txt_tipoCaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_finca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_finca.setForeground(new java.awt.Color(0, 0, 0));
        jb_finca.setText("FINCA:");

        jb_destino.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino.setText("DESTINO:");

        jb_codigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_codigo.setForeground(new java.awt.Color(0, 0, 0));
        jb_codigo.setText("CODIGO:");

        jb_fumigacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fumigacion.setForeground(new java.awt.Color(0, 0, 0));
        jb_fumigacion.setText("FUMIGACION:");

        jb_destino2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino2.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino2.setText("DESTINO:");

        txt_fumigacion.setBackground(new java.awt.Color(255, 255, 255));
        txt_fumigacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino2.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_codigo.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino1.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jcom_finca.setBackground(new java.awt.Color(255, 255, 255));
        jcom_finca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcom_finca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fincas" }));

        redondeado2.setBackground(new java.awt.Color(204, 204, 204));
        redondeado2.setRoundBottomLeft(25);
        redondeado2.setRoundBottomRight(25);
        redondeado2.setRoundTopLeft(25);
        redondeado2.setRoundTopRight(25);
        redondeado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_btn_siguiente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_siguiente.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_siguiente.setText("SIGUIENTE");
        redondeado2.add(jb_btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 13, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp_contenedorGrupoLayout = new javax.swing.GroupLayout(jp_contenedorGrupo);
        jp_contenedorGrupo.setLayout(jp_contenedorGrupoLayout);
        jp_contenedorGrupoLayout.setHorizontalGroup(
            jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addComponent(jb_transporte)
                        .addGap(18, 18, 18)
                        .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_calibracion)
                            .addComponent(jb_vapor)
                            .addComponent(jb_fecha))
                        .addGap(18, 18, 18)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(txt_vapor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_tipoCaja)
                                    .addComponent(jb_finca))
                                .addGap(18, 18, 18)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcom_finca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txt_calibracion))
                                .addGap(41, 41, 41)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jb_lDedos)
                                            .addComponent(jb_pedidos))
                                        .addGap(45, 45, 45)
                                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_dedos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addComponent(jb_semana)
                                        .addGap(45, 45, 45)
                                        .addComponent(jcomb_semana, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addComponent(jb_destino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_destino1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addComponent(jb_codigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addComponent(jb_destino2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_destino2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addComponent(jb_fumigacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                        .addComponent(txt_fumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(redondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        jp_contenedorGrupoLayout.setVerticalGroup(
            jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jb_semana))
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_fecha)
                            .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jb_destino)
                                .addComponent(jcomb_semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_destino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_calibracion)
                    .addComponent(txt_calibracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_lDedos)
                    .addComponent(txt_dedos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_codigo))
                .addGap(35, 35, 35)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_vapor)
                    .addComponent(jb_pedidos)
                    .addComponent(txt_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_fumigacion)
                    .addComponent(txt_fumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_transporte)
                    .addComponent(jb_tipoCaja)
                    .addComponent(txt_tipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_destino2)
                    .addComponent(txt_destino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcom_finca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_finca))
                    .addComponent(redondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jp_contenedorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jp_contenedorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        jTabbedPane1.addTab("DATOS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("TABULACION", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("GENERAR REPORTES", jPanel3);

        javax.swing.GroupLayout jp_lienzoPrincipalLayout = new javax.swing.GroupLayout(jp_lienzoPrincipal);
        jp_lienzoPrincipal.setLayout(jp_lienzoPrincipalLayout);
        jp_lienzoPrincipalLayout.setHorizontalGroup(
            jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jp_lienzoPrincipalLayout.setVerticalGroup(
            jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_calibracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calibracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_calibracionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jb_btn_siguiente;
    private javax.swing.JLabel jb_calibracion;
    private javax.swing.JLabel jb_codigo;
    private javax.swing.JLabel jb_destino;
    private javax.swing.JLabel jb_destino2;
    private javax.swing.JLabel jb_fecha;
    private javax.swing.JLabel jb_finca;
    private javax.swing.JLabel jb_fumigacion;
    private javax.swing.JLabel jb_lDedos;
    private javax.swing.JLabel jb_pedidos;
    private javax.swing.JLabel jb_semana;
    private javax.swing.JLabel jb_tipoCaja;
    private javax.swing.JLabel jb_transporte;
    private javax.swing.JLabel jb_vapor;
    private javax.swing.JComboBox<String> jcom_finca;
    private javax.swing.JComboBox<String> jcomb_semana;
    private javax.swing.JPanel jp_contenedorGrupo;
    private javax.swing.JPanel jp_lienzoPrincipal;
    private Recursos_Codigo.Redondeado redondeado2;
    private javax.swing.JTextField txt_calibracion;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_dedos;
    private javax.swing.JTextField txt_destino1;
    private javax.swing.JTextField txt_destino2;
    private javax.swing.JTextField txt_fumigacion;
    private javax.swing.JTextField txt_pedidos;
    private javax.swing.JTextField txt_tipoCaja;
    private javax.swing.JTextField txt_transporte;
    private javax.swing.JTextField txt_vapor;
    // End of variables declaration//GEN-END:variables
}
