/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Grupo2;

/**
 *
 * @author Daniel Bravo
 */
public class Vis_evaluacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vis_evaluacion
     */
    public Vis_evaluacion() {
        initComponents();

        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_lienzoPrincipal = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        redondeado2 = new Recursos_Codigo.Redondeado();
        jb_btn_siguiente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        redondeado_contenedor_4 = new Recursos_Codigo.Redondeado();
        jp_contenedorGrupo = new javax.swing.JPanel();
        jb_fecha = new javax.swing.JLabel();
        jb_calibracion = new javax.swing.JLabel();
        jb_vapor = new javax.swing.JLabel();
        jb_transporte = new javax.swing.JLabel();
        txt_calibracion = new javax.swing.JTextField();
        txt_vapor = new javax.swing.JTextField();
        txt_transporte = new javax.swing.JTextField();
        jb_semana = new javax.swing.JLabel();
        jcomb_semana = new javax.swing.JComboBox<>();
        jb_lDedos = new javax.swing.JLabel();
        txt_dedos = new javax.swing.JTextField();
        jb_pedidos = new javax.swing.JLabel();
        txt_pedidos = new javax.swing.JTextField();
        jb_tipoCaja = new javax.swing.JLabel();
        txt_tipoCaja = new javax.swing.JTextField();
        jb_finca = new javax.swing.JLabel();
        jb_destino = new javax.swing.JLabel();
        jb_codigo = new javax.swing.JLabel();
        jb_fumigacion = new javax.swing.JLabel();
        jb_destino2 = new javax.swing.JLabel();
        txt_fumigacion = new javax.swing.JTextField();
        txt_destino2 = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_destino1 = new javax.swing.JTextField();
        jcom_finca = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        redondeado_contenedor_2 = new Recursos_Codigo.Redondeado();
        jb_defectos = new javax.swing.JLabel();
        jb_nomb_defecto = new javax.swing.JLabel();
        txt_caja_insp1 = new javax.swing.JTextField();
        jb_contenedor_defecto = new javax.swing.JLabel();
        txt_contenedor = new javax.swing.JTextField();
        redondeado1 = new Recursos_Codigo.Redondeado();
        jb_contenedor_defecto1 = new javax.swing.JLabel();
        redondeado4 = new Recursos_Codigo.Redondeado();
        jb_contenedor_defecto2 = new javax.swing.JLabel();
        redondeado5 = new Recursos_Codigo.Redondeado();
        jb_contenedor_defecto3 = new javax.swing.JLabel();
        redondeado_contenedor_1 = new Recursos_Codigo.Redondeado();
        jb_caja_insp = new javax.swing.JLabel();
        txt_caja_insp = new javax.swing.JTextField();
        jb_total_gajos = new javax.swing.JLabel();
        txt_total_gajos = new javax.swing.JTextField();
        jb_total_gajos1 = new javax.swing.JLabel();
        txt_embalador = new javax.swing.JTextField();
        jb_peso_neto = new javax.swing.JLabel();
        txt_peso_neto = new javax.swing.JTextField();
        jb_gajeo = new javax.swing.JLabel();
        jb_pares = new javax.swing.JLabel();
        txt_pares = new javax.swing.JTextField();
        jb_impares = new javax.swing.JLabel();
        txt_impares = new javax.swing.JTextField();
        redondeado_contenedor_3 = new Recursos_Codigo.Redondeado();
        redondeado6 = new Recursos_Codigo.Redondeado();
        jb_contenedor_defecto4 = new javax.swing.JLabel();
        redondeado7 = new Recursos_Codigo.Redondeado();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jp_lienzoPrincipal1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jp_contenedorGrupo1 = new javax.swing.JPanel();
        jb_fecha1 = new javax.swing.JLabel();
        jb_calibracion1 = new javax.swing.JLabel();
        jb_vapor1 = new javax.swing.JLabel();
        jb_transporte1 = new javax.swing.JLabel();
        txt_calibracion1 = new javax.swing.JTextField();
        txt_vapor1 = new javax.swing.JTextField();
        txt_transporte1 = new javax.swing.JTextField();
        jb_semana1 = new javax.swing.JLabel();
        jcomb_semana1 = new javax.swing.JComboBox<>();
        jb_lDedos1 = new javax.swing.JLabel();
        txt_dedos1 = new javax.swing.JTextField();
        jb_pedidos1 = new javax.swing.JLabel();
        txt_pedidos1 = new javax.swing.JTextField();
        jb_tipoCaja1 = new javax.swing.JLabel();
        txt_tipoCaja1 = new javax.swing.JTextField();
        jb_finca1 = new javax.swing.JLabel();
        jb_destino1 = new javax.swing.JLabel();
        jb_codigo1 = new javax.swing.JLabel();
        jb_fumigacion1 = new javax.swing.JLabel();
        jb_destino3 = new javax.swing.JLabel();
        txt_fumigacion1 = new javax.swing.JTextField();
        txt_destino3 = new javax.swing.JTextField();
        txt_codigo1 = new javax.swing.JTextField();
        txt_destino4 = new javax.swing.JTextField();
        jcom_finca1 = new javax.swing.JComboBox<>();
        redondeado3 = new Recursos_Codigo.Redondeado();
        jb_btn_siguiente1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(965, 605));
        setMinimumSize(new java.awt.Dimension(965, 605));
        setPreferredSize(new java.awt.Dimension(965, 605));

        jp_lienzoPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese todos los datos solicitados.");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido al apartado de Evaluacion  PMCS");

        redondeado2.setBackground(new java.awt.Color(204, 204, 204));
        redondeado2.setRoundBottomLeft(25);
        redondeado2.setRoundBottomRight(25);
        redondeado2.setRoundTopLeft(25);
        redondeado2.setRoundTopRight(25);
        redondeado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_btn_siguiente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_siguiente.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_siguiente.setText("SIGUIENTE");
        redondeado2.add(jb_btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 13, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconSiguienteG2.png"))); // NOI18N
        redondeado2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 4, -1, 30));

        redondeado_contenedor_4.setBackground(new java.awt.Color(204, 204, 255));
        redondeado_contenedor_4.setRoundBottomLeft(30);
        redondeado_contenedor_4.setRoundBottomRight(30);
        redondeado_contenedor_4.setRoundTopLeft(30);
        redondeado_contenedor_4.setRoundTopRight(30);

        jp_contenedorGrupo.setBackground(new java.awt.Color(204, 204, 255));

        jb_fecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fecha.setForeground(new java.awt.Color(0, 0, 0));
        jb_fecha.setText("FECHA:");

        jb_calibracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_calibracion.setForeground(new java.awt.Color(0, 0, 0));
        jb_calibracion.setText("CALIBRACION:");

        jb_vapor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_vapor.setForeground(new java.awt.Color(0, 0, 0));
        jb_vapor.setText("VAPOR:");

        jb_transporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_transporte.setForeground(new java.awt.Color(0, 0, 0));
        jb_transporte.setText("TRANSPORTE:");

        txt_calibracion.setBackground(new java.awt.Color(255, 255, 255));
        txt_calibracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_calibracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calibracionActionPerformed(evt);
            }
        });

        txt_vapor.setBackground(new java.awt.Color(255, 255, 255));
        txt_vapor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_transporte.setBackground(new java.awt.Color(255, 255, 255));
        txt_transporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_semana.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_semana.setForeground(new java.awt.Color(0, 0, 0));
        jb_semana.setText("SEMANA:");

        jcomb_semana.setBackground(new java.awt.Color(255, 255, 255));
        jcomb_semana.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcomb_semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanas" }));

        jb_lDedos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_lDedos.setForeground(new java.awt.Color(0, 0, 0));
        jb_lDedos.setText("L. DEDOS:");

        txt_dedos.setBackground(new java.awt.Color(255, 255, 255));
        txt_dedos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_pedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_pedidos.setForeground(new java.awt.Color(0, 0, 0));
        jb_pedidos.setText("PEDIDO:");

        txt_pedidos.setBackground(new java.awt.Color(255, 255, 255));
        txt_pedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_tipoCaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_tipoCaja.setForeground(new java.awt.Color(0, 0, 0));
        jb_tipoCaja.setText("TIPO DE CAJA:");

        txt_tipoCaja.setBackground(new java.awt.Color(255, 255, 255));
        txt_tipoCaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_finca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_finca.setForeground(new java.awt.Color(0, 0, 0));
        jb_finca.setText("FINCA:");

        jb_destino.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino.setText("DESTINO:");

        jb_codigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_codigo.setForeground(new java.awt.Color(0, 0, 0));
        jb_codigo.setText("CODIGO:");

        jb_fumigacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fumigacion.setForeground(new java.awt.Color(0, 0, 0));
        jb_fumigacion.setText("FUMIGACION:");

        jb_destino2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino2.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino2.setText("DESTINO:");

        txt_fumigacion.setBackground(new java.awt.Color(255, 255, 255));
        txt_fumigacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino2.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_codigo.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino1.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jcom_finca.setBackground(new java.awt.Color(255, 255, 255));
        jcom_finca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcom_finca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fincas" }));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp_contenedorGrupoLayout = new javax.swing.GroupLayout(jp_contenedorGrupo);
        jp_contenedorGrupo.setLayout(jp_contenedorGrupoLayout);
        jp_contenedorGrupoLayout.setHorizontalGroup(
            jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addComponent(jb_transporte)
                        .addGap(18, 18, 18)
                        .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_calibracion)
                                    .addComponent(jb_vapor)
                                    .addComponent(jb_fecha))
                                .addGap(18, 18, 18)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_calibracion)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jb_lDedos)
                                            .addComponent(jb_pedidos)))
                                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jb_semana)))
                                .addGap(45, 45, 45)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcomb_semana, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_dedos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(txt_vapor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_tipoCaja)
                                    .addComponent(jb_finca))
                                .addGap(18, 18, 18)
                                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcom_finca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_destino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_destino1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_destino2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_destino2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_fumigacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(txt_fumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jp_contenedorGrupoLayout.setVerticalGroup(
            jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_semana)
                        .addComponent(jcomb_semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_destino)
                        .addComponent(txt_destino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_fecha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_calibracion)
                    .addComponent(txt_calibracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_lDedos)
                    .addComponent(txt_dedos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_codigo))
                .addGap(35, 35, 35)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_vapor)
                    .addComponent(jb_pedidos)
                    .addComponent(txt_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_fumigacion)
                    .addComponent(txt_fumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_transporte)
                    .addComponent(jb_tipoCaja)
                    .addComponent(txt_tipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_destino2)
                    .addComponent(txt_destino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcom_finca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_finca))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout redondeado_contenedor_4Layout = new javax.swing.GroupLayout(redondeado_contenedor_4);
        redondeado_contenedor_4.setLayout(redondeado_contenedor_4Layout);
        redondeado_contenedor_4Layout.setHorizontalGroup(
            redondeado_contenedor_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redondeado_contenedor_4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jp_contenedorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        redondeado_contenedor_4Layout.setVerticalGroup(
            redondeado_contenedor_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redondeado_contenedor_4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jp_contenedorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(redondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redondeado_contenedor_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redondeado_contenedor_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("DATOS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        redondeado_contenedor_2.setBackground(new java.awt.Color(204, 204, 255));
        redondeado_contenedor_2.setRoundBottomLeft(30);
        redondeado_contenedor_2.setRoundBottomRight(30);
        redondeado_contenedor_2.setRoundTopLeft(30);
        redondeado_contenedor_2.setRoundTopRight(30);

        jb_defectos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jb_defectos.setForeground(new java.awt.Color(0, 0, 0));
        jb_defectos.setText("DEFECTOS ENCONTRADOS");

        jb_nomb_defecto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_nomb_defecto.setForeground(new java.awt.Color(0, 0, 0));
        jb_nomb_defecto.setText("NOMBRE:");

        txt_caja_insp1.setBackground(new java.awt.Color(255, 255, 255));

        jb_contenedor_defecto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_contenedor_defecto.setForeground(new java.awt.Color(0, 0, 0));
        jb_contenedor_defecto.setText("CONTENEDOR:");

        txt_contenedor.setBackground(new java.awt.Color(255, 255, 255));

        redondeado1.setBackground(new java.awt.Color(153, 153, 153));
        redondeado1.setRoundBottomLeft(25);
        redondeado1.setRoundBottomRight(25);
        redondeado1.setRoundTopLeft(25);
        redondeado1.setRoundTopRight(25);
        redondeado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_contenedor_defecto1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_contenedor_defecto1.setForeground(new java.awt.Color(0, 0, 0));
        jb_contenedor_defecto1.setText("AGREGAR DEFECTOS");
        redondeado1.add(jb_contenedor_defecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        redondeado4.setBackground(new java.awt.Color(153, 153, 153));
        redondeado4.setRoundBottomLeft(25);
        redondeado4.setRoundBottomRight(25);
        redondeado4.setRoundTopLeft(25);
        redondeado4.setRoundTopRight(25);
        redondeado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_contenedor_defecto2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_contenedor_defecto2.setForeground(new java.awt.Color(0, 0, 0));
        jb_contenedor_defecto2.setText("NUEVOS DATOS");
        redondeado4.add(jb_contenedor_defecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        redondeado5.setBackground(new java.awt.Color(153, 153, 153));
        redondeado5.setRoundBottomLeft(25);
        redondeado5.setRoundBottomRight(25);
        redondeado5.setRoundTopLeft(25);
        redondeado5.setRoundTopRight(25);
        redondeado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_contenedor_defecto3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_contenedor_defecto3.setForeground(new java.awt.Color(0, 0, 0));
        jb_contenedor_defecto3.setText("NUEVOS DATOS");
        redondeado5.add(jb_contenedor_defecto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        redondeado4.add(redondeado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout redondeado_contenedor_2Layout = new javax.swing.GroupLayout(redondeado_contenedor_2);
        redondeado_contenedor_2.setLayout(redondeado_contenedor_2Layout);
        redondeado_contenedor_2Layout.setHorizontalGroup(
            redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redondeado_contenedor_2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_defectos)
                    .addGroup(redondeado_contenedor_2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(redondeado_contenedor_2Layout.createSequentialGroup()
                                .addComponent(jb_contenedor_defecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(redondeado_contenedor_2Layout.createSequentialGroup()
                                .addComponent(jb_nomb_defecto)
                                .addGap(57, 57, 57)
                                .addComponent(txt_caja_insp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(redondeado_contenedor_2Layout.createSequentialGroup()
                        .addComponent(redondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redondeado4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        redondeado_contenedor_2Layout.setVerticalGroup(
            redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redondeado_contenedor_2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jb_defectos)
                .addGap(14, 14, 14)
                .addGroup(redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_caja_insp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nomb_defecto))
                .addGap(18, 18, 18)
                .addGroup(redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_contenedor_defecto)
                    .addComponent(txt_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(redondeado_contenedor_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(redondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redondeado4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        redondeado_contenedor_1.setBackground(new java.awt.Color(204, 204, 255));
        redondeado_contenedor_1.setRoundBottomLeft(30);
        redondeado_contenedor_1.setRoundBottomRight(30);
        redondeado_contenedor_1.setRoundTopLeft(30);
        redondeado_contenedor_1.setRoundTopRight(30);

        jb_caja_insp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_caja_insp.setForeground(new java.awt.Color(0, 0, 0));
        jb_caja_insp.setText("CAJA INSPECCIONADA:");

        txt_caja_insp.setBackground(new java.awt.Color(255, 255, 255));

        jb_total_gajos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_total_gajos.setForeground(new java.awt.Color(0, 0, 0));
        jb_total_gajos.setText("EMBALADOR:");

        txt_total_gajos.setBackground(new java.awt.Color(255, 255, 255));

        jb_total_gajos1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_total_gajos1.setForeground(new java.awt.Color(0, 0, 0));
        jb_total_gajos1.setText("TOTAL DE GAJOS:");

        txt_embalador.setBackground(new java.awt.Color(255, 255, 255));

        jb_peso_neto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_peso_neto.setForeground(new java.awt.Color(0, 0, 0));
        jb_peso_neto.setText("PESO NETO:");

        txt_peso_neto.setBackground(new java.awt.Color(255, 255, 255));

        jb_gajeo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_gajeo.setForeground(new java.awt.Color(0, 0, 0));
        jb_gajeo.setText("% GAJEO");

        jb_pares.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_pares.setForeground(new java.awt.Color(0, 0, 0));
        jb_pares.setText("PARES:");

        txt_pares.setBackground(new java.awt.Color(255, 255, 255));

        jb_impares.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_impares.setForeground(new java.awt.Color(0, 0, 0));
        jb_impares.setText("IMPARES:");

        txt_impares.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout redondeado_contenedor_1Layout = new javax.swing.GroupLayout(redondeado_contenedor_1);
        redondeado_contenedor_1.setLayout(redondeado_contenedor_1Layout);
        redondeado_contenedor_1Layout.setHorizontalGroup(
            redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redondeado_contenedor_1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_caja_insp)
                    .addComponent(jb_total_gajos1))
                .addGap(18, 18, 18)
                .addGroup(redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_caja_insp, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(txt_total_gajos))
                .addGap(33, 33, 33)
                .addGroup(redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(redondeado_contenedor_1Layout.createSequentialGroup()
                        .addComponent(jb_total_gajos)
                        .addGap(18, 18, 18)
                        .addComponent(txt_embalador, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(redondeado_contenedor_1Layout.createSequentialGroup()
                        .addComponent(jb_peso_neto)
                        .addGap(25, 25, 25)
                        .addComponent(txt_peso_neto, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                .addGroup(redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(redondeado_contenedor_1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jb_pares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_impares)
                        .addGap(14, 14, 14)
                        .addComponent(txt_impares)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redondeado_contenedor_1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_gajeo)
                        .addGap(152, 152, 152))))
        );
        redondeado_contenedor_1Layout.setVerticalGroup(
            redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redondeado_contenedor_1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_caja_insp)
                    .addComponent(txt_caja_insp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_total_gajos)
                    .addComponent(txt_embalador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_gajeo))
                .addGap(18, 18, 18)
                .addGroup(redondeado_contenedor_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total_gajos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_peso_neto)
                    .addComponent(txt_peso_neto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_pares)
                    .addComponent(txt_pares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_impares)
                    .addComponent(txt_impares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_total_gajos1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        redondeado_contenedor_3.setBackground(new java.awt.Color(204, 204, 255));
        redondeado_contenedor_3.setRoundBottomLeft(30);
        redondeado_contenedor_3.setRoundBottomRight(30);
        redondeado_contenedor_3.setRoundTopLeft(30);
        redondeado_contenedor_3.setRoundTopRight(30);

        javax.swing.GroupLayout redondeado_contenedor_3Layout = new javax.swing.GroupLayout(redondeado_contenedor_3);
        redondeado_contenedor_3.setLayout(redondeado_contenedor_3Layout);
        redondeado_contenedor_3Layout.setHorizontalGroup(
            redondeado_contenedor_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        redondeado_contenedor_3Layout.setVerticalGroup(
            redondeado_contenedor_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        redondeado6.setBackground(new java.awt.Color(153, 153, 153));
        redondeado6.setRoundBottomLeft(25);
        redondeado6.setRoundBottomRight(25);
        redondeado6.setRoundTopLeft(25);
        redondeado6.setRoundTopRight(25);
        redondeado6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_contenedor_defecto4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_contenedor_defecto4.setForeground(new java.awt.Color(0, 0, 0));
        jb_contenedor_defecto4.setText("GENERAR REPORTE");
        redondeado6.add(jb_contenedor_defecto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        redondeado7.setBackground(new java.awt.Color(153, 153, 153));
        redondeado7.setRoundBottomLeft(25);
        redondeado7.setRoundBottomRight(25);
        redondeado7.setRoundTopLeft(25);
        redondeado7.setRoundTopRight(25);
        redondeado7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        redondeado6.add(redondeado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redondeado_contenedor_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redondeado_contenedor_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redondeado_contenedor_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(redondeado6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redondeado_contenedor_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redondeado_contenedor_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redondeado_contenedor_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redondeado6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("TABULACION", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("GENERAR REPORTES", jPanel3);

        javax.swing.GroupLayout jp_lienzoPrincipalLayout = new javax.swing.GroupLayout(jp_lienzoPrincipal);
        jp_lienzoPrincipal.setLayout(jp_lienzoPrincipalLayout);
        jp_lienzoPrincipalLayout.setHorizontalGroup(
            jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jp_lienzoPrincipalLayout.setVerticalGroup(
            jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setMaximumSize(new java.awt.Dimension(965, 605));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(965, 605));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(965, 605));

        jp_lienzoPrincipal1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedorGrupo1.setBackground(new java.awt.Color(255, 255, 255));

        jb_fecha1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fecha1.setForeground(new java.awt.Color(0, 0, 0));
        jb_fecha1.setText("FECHA:");

        jb_calibracion1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_calibracion1.setForeground(new java.awt.Color(0, 0, 0));
        jb_calibracion1.setText("CALIBRACION:");

        jb_vapor1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_vapor1.setForeground(new java.awt.Color(0, 0, 0));
        jb_vapor1.setText("VAPOR:");

        jb_transporte1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_transporte1.setForeground(new java.awt.Color(0, 0, 0));
        jb_transporte1.setText("TRANSPORTE:");

        txt_calibracion1.setBackground(new java.awt.Color(255, 255, 255));
        txt_calibracion1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_calibracion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calibracion1ActionPerformed(evt);
            }
        });

        txt_vapor1.setBackground(new java.awt.Color(255, 255, 255));
        txt_vapor1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_transporte1.setBackground(new java.awt.Color(255, 255, 255));
        txt_transporte1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_semana1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_semana1.setForeground(new java.awt.Color(0, 0, 0));
        jb_semana1.setText("SEMANA:");

        jcomb_semana1.setBackground(new java.awt.Color(255, 255, 255));
        jcomb_semana1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcomb_semana1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanas" }));

        jb_lDedos1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_lDedos1.setForeground(new java.awt.Color(0, 0, 0));
        jb_lDedos1.setText("L. DEDOS:");

        txt_dedos1.setBackground(new java.awt.Color(255, 255, 255));
        txt_dedos1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_pedidos1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_pedidos1.setForeground(new java.awt.Color(0, 0, 0));
        jb_pedidos1.setText("PEDIDO:");

        txt_pedidos1.setBackground(new java.awt.Color(255, 255, 255));
        txt_pedidos1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_tipoCaja1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_tipoCaja1.setForeground(new java.awt.Color(0, 0, 0));
        jb_tipoCaja1.setText("TIPO DE CAJA:");

        txt_tipoCaja1.setBackground(new java.awt.Color(255, 255, 255));
        txt_tipoCaja1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_finca1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_finca1.setForeground(new java.awt.Color(0, 0, 0));
        jb_finca1.setText("FINCA:");

        jb_destino1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino1.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino1.setText("DESTINO:");

        jb_codigo1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_codigo1.setForeground(new java.awt.Color(0, 0, 0));
        jb_codigo1.setText("CODIGO:");

        jb_fumigacion1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fumigacion1.setForeground(new java.awt.Color(0, 0, 0));
        jb_fumigacion1.setText("FUMIGACION:");

        jb_destino3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino3.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino3.setText("DESTINO:");

        txt_fumigacion1.setBackground(new java.awt.Color(255, 255, 255));
        txt_fumigacion1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino3.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_codigo1.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino4.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jcom_finca1.setBackground(new java.awt.Color(255, 255, 255));
        jcom_finca1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcom_finca1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fincas" }));

        redondeado3.setBackground(new java.awt.Color(204, 204, 204));
        redondeado3.setRoundBottomLeft(25);
        redondeado3.setRoundBottomRight(25);
        redondeado3.setRoundTopLeft(25);
        redondeado3.setRoundTopRight(25);
        redondeado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_btn_siguiente1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_siguiente1.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_siguiente1.setText("SIGUIENTE");
        redondeado3.add(jb_btn_siguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 13, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconSiguienteG2.png"))); // NOI18N
        redondeado3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 4, -1, 30));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp_contenedorGrupo1Layout = new javax.swing.GroupLayout(jp_contenedorGrupo1);
        jp_contenedorGrupo1.setLayout(jp_contenedorGrupo1Layout);
        jp_contenedorGrupo1Layout.setHorizontalGroup(
            jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                        .addComponent(jb_transporte1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_transporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 503, Short.MAX_VALUE))
                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                        .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_calibracion1)
                                    .addComponent(jb_vapor1)
                                    .addComponent(jb_fecha1))
                                .addGap(18, 18, 18)
                                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_calibracion1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                        .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jb_lDedos1)
                                            .addComponent(jb_pedidos1))
                                        .addGap(45, 45, 45)
                                        .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_pedidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_dedos1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorGrupo1Layout.createSequentialGroup()
                                        .addComponent(jb_semana1)
                                        .addGap(45, 45, 45)
                                        .addComponent(jcomb_semana1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(txt_vapor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_tipoCaja1)
                                    .addComponent(jb_finca1))
                                .addGap(18, 18, 18)
                                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcom_finca1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tipoCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                        .addComponent(jb_destino1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_destino4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                        .addComponent(jb_codigo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                        .addComponent(jb_destino3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_destino3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                        .addComponent(jb_fumigacion1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_fumigacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(redondeado3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jp_contenedorGrupo1Layout.setVerticalGroup(
            jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jb_semana1))
                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_fecha1)
                            .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jb_destino1)
                                .addComponent(jcomb_semana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_destino4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_contenedorGrupo1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_calibracion1)
                    .addComponent(txt_calibracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_lDedos1)
                    .addComponent(txt_dedos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_codigo1))
                .addGap(35, 35, 35)
                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vapor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_vapor1)
                    .addComponent(jb_pedidos1)
                    .addComponent(txt_pedidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_fumigacion1)
                    .addComponent(txt_fumigacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_transporte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_transporte1)
                    .addComponent(jb_tipoCaja1)
                    .addComponent(txt_tipoCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_destino3)
                    .addComponent(txt_destino3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcom_finca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_finca1))
                    .addComponent(redondeado3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese todos los datos solicitados.");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Bienvenido al apartado de Evaluacion  PMCS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jp_contenedorGrupo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addComponent(jp_contenedorGrupo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("DATOS", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("TABULACION", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("GENERAR REPORTES", jPanel6);

        javax.swing.GroupLayout jp_lienzoPrincipal1Layout = new javax.swing.GroupLayout(jp_lienzoPrincipal1);
        jp_lienzoPrincipal1.setLayout(jp_lienzoPrincipal1Layout);
        jp_lienzoPrincipal1Layout.setHorizontalGroup(
            jp_lienzoPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jp_lienzoPrincipal1Layout.setVerticalGroup(
            jp_lienzoPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 290, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 291, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_calibracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calibracionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_calibracionActionPerformed

    private void txt_calibracion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calibracion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_calibracion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jb_btn_siguiente;
    private javax.swing.JLabel jb_btn_siguiente1;
    private javax.swing.JLabel jb_caja_insp;
    private javax.swing.JLabel jb_calibracion;
    private javax.swing.JLabel jb_calibracion1;
    private javax.swing.JLabel jb_codigo;
    private javax.swing.JLabel jb_codigo1;
    private javax.swing.JLabel jb_contenedor_defecto;
    private javax.swing.JLabel jb_contenedor_defecto1;
    private javax.swing.JLabel jb_contenedor_defecto2;
    private javax.swing.JLabel jb_contenedor_defecto3;
    private javax.swing.JLabel jb_contenedor_defecto4;
    private javax.swing.JLabel jb_defectos;
    private javax.swing.JLabel jb_destino;
    private javax.swing.JLabel jb_destino1;
    private javax.swing.JLabel jb_destino2;
    private javax.swing.JLabel jb_destino3;
    private javax.swing.JLabel jb_fecha;
    private javax.swing.JLabel jb_fecha1;
    private javax.swing.JLabel jb_finca;
    private javax.swing.JLabel jb_finca1;
    private javax.swing.JLabel jb_fumigacion;
    private javax.swing.JLabel jb_fumigacion1;
    private javax.swing.JLabel jb_gajeo;
    private javax.swing.JLabel jb_impares;
    private javax.swing.JLabel jb_lDedos;
    private javax.swing.JLabel jb_lDedos1;
    private javax.swing.JLabel jb_nomb_defecto;
    private javax.swing.JLabel jb_pares;
    private javax.swing.JLabel jb_pedidos;
    private javax.swing.JLabel jb_pedidos1;
    private javax.swing.JLabel jb_peso_neto;
    private javax.swing.JLabel jb_semana;
    private javax.swing.JLabel jb_semana1;
    private javax.swing.JLabel jb_tipoCaja;
    private javax.swing.JLabel jb_tipoCaja1;
    private javax.swing.JLabel jb_total_gajos;
    private javax.swing.JLabel jb_total_gajos1;
    private javax.swing.JLabel jb_transporte;
    private javax.swing.JLabel jb_transporte1;
    private javax.swing.JLabel jb_vapor;
    private javax.swing.JLabel jb_vapor1;
    private javax.swing.JComboBox<String> jcom_finca;
    private javax.swing.JComboBox<String> jcom_finca1;
    private javax.swing.JComboBox<String> jcomb_semana;
    private javax.swing.JComboBox<String> jcomb_semana1;
    private javax.swing.JPanel jp_contenedorGrupo;
    private javax.swing.JPanel jp_contenedorGrupo1;
    private javax.swing.JPanel jp_lienzoPrincipal;
    private javax.swing.JPanel jp_lienzoPrincipal1;
    private Recursos_Codigo.Redondeado redondeado1;
    private Recursos_Codigo.Redondeado redondeado2;
    private Recursos_Codigo.Redondeado redondeado3;
    private Recursos_Codigo.Redondeado redondeado4;
    private Recursos_Codigo.Redondeado redondeado5;
    private Recursos_Codigo.Redondeado redondeado6;
    private Recursos_Codigo.Redondeado redondeado7;
    private Recursos_Codigo.Redondeado redondeado_contenedor_1;
    private Recursos_Codigo.Redondeado redondeado_contenedor_2;
    private Recursos_Codigo.Redondeado redondeado_contenedor_3;
    private Recursos_Codigo.Redondeado redondeado_contenedor_4;
    private javax.swing.JTextField txt_caja_insp;
    private javax.swing.JTextField txt_caja_insp1;
    private javax.swing.JTextField txt_calibracion;
    private javax.swing.JTextField txt_calibracion1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigo1;
    private javax.swing.JTextField txt_contenedor;
    private javax.swing.JTextField txt_dedos;
    private javax.swing.JTextField txt_dedos1;
    private javax.swing.JTextField txt_destino1;
    private javax.swing.JTextField txt_destino2;
    private javax.swing.JTextField txt_destino3;
    private javax.swing.JTextField txt_destino4;
    private javax.swing.JTextField txt_embalador;
    private javax.swing.JTextField txt_fumigacion;
    private javax.swing.JTextField txt_fumigacion1;
    private javax.swing.JTextField txt_impares;
    private javax.swing.JTextField txt_pares;
    private javax.swing.JTextField txt_pedidos;
    private javax.swing.JTextField txt_pedidos1;
    private javax.swing.JTextField txt_peso_neto;
    private javax.swing.JTextField txt_tipoCaja;
    private javax.swing.JTextField txt_tipoCaja1;
    private javax.swing.JTextField txt_total_gajos;
    private javax.swing.JTextField txt_transporte;
    private javax.swing.JTextField txt_transporte1;
    private javax.swing.JTextField txt_vapor;
    private javax.swing.JTextField txt_vapor1;
    // End of variables declaration//GEN-END:variables
}
