/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Grupo2;

/**
 *
 * @author Daniel Bravo
 */
public class Vis_evaluacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vis_evaluacion
     */
    public Vis_evaluacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_lienzoPrincipal = new javax.swing.JPanel();
        jp_contenedorGrupo = new javax.swing.JPanel();
        jb_fecha = new javax.swing.JLabel();
        jb_calibracion = new javax.swing.JLabel();
        jb_vapor = new javax.swing.JLabel();
        jb_transporte = new javax.swing.JLabel();
        txt_calibracion = new javax.swing.JTextField();
        txt_vapor = new javax.swing.JTextField();
        txt_transporte = new javax.swing.JTextField();
        jb_semana = new javax.swing.JLabel();
        jcomb_semana = new javax.swing.JComboBox<>();
        jb_lDedos = new javax.swing.JLabel();
        txt_dedos = new javax.swing.JTextField();
        jb_pedidos = new javax.swing.JLabel();
        txt_pedidos = new javax.swing.JTextField();
        jb_tipoCaja = new javax.swing.JLabel();
        txt_tipoCaja = new javax.swing.JTextField();
        jb_finca = new javax.swing.JLabel();
        jb_destino = new javax.swing.JLabel();
        jb_codigo = new javax.swing.JLabel();
        jb_fumigacion = new javax.swing.JLabel();
        jb_destino2 = new javax.swing.JLabel();
        txt_fumigacion = new javax.swing.JTextField();
        txt_destino2 = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_destino1 = new javax.swing.JTextField();
        jcom_finca = new javax.swing.JComboBox<>();
        btn_siguiente1 = new Controlador.Redondeado();
        jb_btn_reporte = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jb_btn_tabulacion1 = new javax.swing.JLabel();
        jb_btn_datos2 = new javax.swing.JLabel();
        btn_siguiente = new Controlador.Redondeado();
        jb_btn_siguiente = new javax.swing.JLabel();

        jp_lienzoPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedorGrupo.setBackground(new java.awt.Color(255, 255, 255));

        jb_fecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fecha.setForeground(new java.awt.Color(0, 0, 0));
        jb_fecha.setText("FECHA:");

        jb_calibracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_calibracion.setForeground(new java.awt.Color(0, 0, 0));
        jb_calibracion.setText("CALIBRACION:");

        jb_vapor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_vapor.setForeground(new java.awt.Color(0, 0, 0));
        jb_vapor.setText("VAPOR:");

        jb_transporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_transporte.setForeground(new java.awt.Color(0, 0, 0));
        jb_transporte.setText("TRANSPORTE:");

        txt_calibracion.setBackground(new java.awt.Color(255, 255, 255));
        txt_calibracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_vapor.setBackground(new java.awt.Color(255, 255, 255));
        txt_vapor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_transporte.setBackground(new java.awt.Color(255, 255, 255));
        txt_transporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_semana.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_semana.setForeground(new java.awt.Color(0, 0, 0));
        jb_semana.setText("SEMANA:");

        jcomb_semana.setBackground(new java.awt.Color(255, 255, 255));
        jcomb_semana.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcomb_semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanas" }));

        jb_lDedos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_lDedos.setForeground(new java.awt.Color(0, 0, 0));
        jb_lDedos.setText("L. DEDOS:");

        txt_dedos.setBackground(new java.awt.Color(255, 255, 255));
        txt_dedos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_pedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_pedidos.setForeground(new java.awt.Color(0, 0, 0));
        jb_pedidos.setText("PEDIDO:");

        txt_pedidos.setBackground(new java.awt.Color(255, 255, 255));
        txt_pedidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_tipoCaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_tipoCaja.setForeground(new java.awt.Color(0, 0, 0));
        jb_tipoCaja.setText("TIPO DE CAJA:");

        txt_tipoCaja.setBackground(new java.awt.Color(255, 255, 255));
        txt_tipoCaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jb_finca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_finca.setForeground(new java.awt.Color(0, 0, 0));
        jb_finca.setText("FINCA:");

        jb_destino.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino.setText("DESTINO:");

        jb_codigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_codigo.setForeground(new java.awt.Color(0, 0, 0));
        jb_codigo.setText("CODIGO:");

        jb_fumigacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_fumigacion.setForeground(new java.awt.Color(0, 0, 0));
        jb_fumigacion.setText("FUMIGACION:");

        jb_destino2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_destino2.setForeground(new java.awt.Color(0, 0, 0));
        jb_destino2.setText("DESTINO:");

        txt_fumigacion.setBackground(new java.awt.Color(255, 255, 255));
        txt_fumigacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino2.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_codigo.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txt_destino1.setBackground(new java.awt.Color(255, 255, 255));
        txt_destino1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jcom_finca.setBackground(new java.awt.Color(255, 255, 255));
        jcom_finca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcom_finca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fincas" }));

        javax.swing.GroupLayout jp_contenedorGrupoLayout = new javax.swing.GroupLayout(jp_contenedorGrupo);
        jp_contenedorGrupo.setLayout(jp_contenedorGrupoLayout);
        jp_contenedorGrupoLayout.setHorizontalGroup(
            jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jb_transporte)
                                .addGap(18, 18, 18)
                                .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jb_tipoCaja)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jb_finca)
                                .addGap(60, 60, 60)
                                .addComponent(jcom_finca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(jb_destino2)
                        .addGap(34, 34, 34)
                        .addComponent(txt_destino2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_fecha)
                                .addGap(189, 189, 189)
                                .addComponent(jb_semana)
                                .addGap(45, 45, 45)
                                .addComponent(jcomb_semana, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jb_destino)
                                .addGap(34, 34, 34)
                                .addComponent(txt_destino1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_calibracion)
                                .addGap(18, 18, 18)
                                .addComponent(txt_calibracion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jb_lDedos)
                                .addGap(45, 45, 45)
                                .addComponent(txt_dedos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jb_codigo)
                                .addGap(41, 41, 41)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                                .addComponent(jb_vapor)
                                .addGap(55, 55, 55)
                                .addComponent(txt_vapor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jb_pedidos)
                                .addGap(54, 54, 54)
                                .addComponent(txt_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jb_fumigacion)
                                .addGap(12, 12, 12)
                                .addComponent(txt_fumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jp_contenedorGrupoLayout.setVerticalGroup(
            jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcomb_semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_destino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_fecha)
                            .addComponent(jb_semana)
                            .addComponent(jb_destino))))
                .addGap(19, 19, 19)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_calibracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dedos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_calibracion)
                            .addComponent(jb_lDedos)
                            .addComponent(jb_codigo))))
                .addGap(18, 18, 18)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_vapor)
                    .addComponent(txt_vapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_pedidos)
                            .addComponent(jb_fumigacion))))
                .addGap(19, 19, 19)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tipoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_destino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_transporte)
                            .addComponent(jb_tipoCaja)
                            .addComponent(jb_destino2))))
                .addGap(17, 17, 17)
                .addGroup(jp_contenedorGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorGrupoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jb_finca))
                    .addComponent(jcom_finca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btn_siguiente1.setBackground(new java.awt.Color(204, 204, 204));
        btn_siguiente1.setRoundBottomLeft(15);
        btn_siguiente1.setRoundBottomRight(15);
        btn_siguiente1.setRoundTopLeft(15);
        btn_siguiente1.setRoundTopRight(15);
        btn_siguiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_btn_reporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_reporte.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_reporte.setText("GENERAR REPORTE");
        btn_siguiente1.add(jb_btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        btn_siguiente1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 18, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        btn_siguiente1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 18, 30));

        jb_btn_tabulacion1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_tabulacion1.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_tabulacion1.setText("TABULACION");
        btn_siguiente1.add(jb_btn_tabulacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jb_btn_datos2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_datos2.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_datos2.setText("DATOS");
        btn_siguiente1.add(jb_btn_datos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        btn_siguiente.setBackground(new java.awt.Color(204, 204, 204));
        btn_siguiente.setRoundBottomLeft(15);
        btn_siguiente.setRoundBottomRight(15);
        btn_siguiente.setRoundTopLeft(15);
        btn_siguiente.setRoundTopRight(15);

        jb_btn_siguiente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jb_btn_siguiente.setForeground(new java.awt.Color(0, 0, 0));
        jb_btn_siguiente.setText("SIGUIENTE");

        javax.swing.GroupLayout btn_siguienteLayout = new javax.swing.GroupLayout(btn_siguiente);
        btn_siguiente.setLayout(btn_siguienteLayout);
        btn_siguienteLayout.setHorizontalGroup(
            btn_siguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_siguienteLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jb_btn_siguiente)
                .addGap(33, 33, 33))
        );
        btn_siguienteLayout.setVerticalGroup(
            btn_siguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_siguienteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jb_btn_siguiente)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_lienzoPrincipalLayout = new javax.swing.GroupLayout(jp_lienzoPrincipal);
        jp_lienzoPrincipal.setLayout(jp_lienzoPrincipalLayout);
        jp_lienzoPrincipalLayout.setHorizontalGroup(
            jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_lienzoPrincipalLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_contenedorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(jp_lienzoPrincipalLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_lienzoPrincipalLayout.setVerticalGroup(
            jp_lienzoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_lienzoPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btn_siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jp_contenedorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lienzoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controlador.Redondeado btn_siguiente;
    private Controlador.Redondeado btn_siguiente1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jb_btn_datos2;
    private javax.swing.JLabel jb_btn_reporte;
    private javax.swing.JLabel jb_btn_siguiente;
    private javax.swing.JLabel jb_btn_tabulacion1;
    private javax.swing.JLabel jb_calibracion;
    private javax.swing.JLabel jb_codigo;
    private javax.swing.JLabel jb_destino;
    private javax.swing.JLabel jb_destino2;
    private javax.swing.JLabel jb_fecha;
    private javax.swing.JLabel jb_finca;
    private javax.swing.JLabel jb_fumigacion;
    private javax.swing.JLabel jb_lDedos;
    private javax.swing.JLabel jb_pedidos;
    private javax.swing.JLabel jb_semana;
    private javax.swing.JLabel jb_tipoCaja;
    private javax.swing.JLabel jb_transporte;
    private javax.swing.JLabel jb_vapor;
    private javax.swing.JComboBox<String> jcom_finca;
    private javax.swing.JComboBox<String> jcomb_semana;
    private javax.swing.JPanel jp_contenedorGrupo;
    private javax.swing.JPanel jp_lienzoPrincipal;
    private Controlador.Redondeado redondeado3;
    private javax.swing.JTextField txt_calibracion;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_dedos;
    private javax.swing.JTextField txt_destino1;
    private javax.swing.JTextField txt_destino2;
    private javax.swing.JTextField txt_fumigacion;
    private javax.swing.JTextField txt_pedidos;
    private javax.swing.JTextField txt_tipoCaja;
    private javax.swing.JTextField txt_transporte;
    private javax.swing.JTextField txt_vapor;
    // End of variables declaration//GEN-END:variables
}
