/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Grupo2;

/**
 *
 * @author Daniel Bravo
 */
public class Vista_Reportes_Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Reportes_Menu
     */
    public Vista_Reportes_Menu() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto_inicio = new javax.swing.JLabel();
        rdn_buscar = new Recursos_Codigo.Redondeado();
        txt_buscar = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reportes = new javax.swing.JTable();
        rdn_imprimir = new Recursos_Codigo.Redondeado();
        jb_actualizar = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(965, 629));
        setMinimumSize(new java.awt.Dimension(965, 629));
        setPreferredSize(new java.awt.Dimension(965, 629));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        texto_inicio.setFont(new java.awt.Font("Roboto Black", 1, 34)); // NOI18N
        texto_inicio.setForeground(new java.awt.Color(0, 0, 0));
        texto_inicio.setText("LISTADO DE REPORTES DE EVALUACION PCMS");

        rdn_buscar.setBackground(new java.awt.Color(255, 255, 255));
        rdn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        rdn_buscar.setRoundBottomLeft(30);
        rdn_buscar.setRoundBottomRight(30);
        rdn_buscar.setRoundTopLeft(30);
        rdn_buscar.setRoundTopRight(30);

        txt_buscar.setBackground(new java.awt.Color(255, 255, 255));
        txt_buscar.setText("Buscar");
        txt_buscar.setBorder(null);
        txt_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-búsqueda-28.png"))); // NOI18N
        jb_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout rdn_buscarLayout = new javax.swing.GroupLayout(rdn_buscar);
        rdn_buscar.setLayout(rdn_buscarLayout);
        rdn_buscarLayout.setHorizontalGroup(
            rdn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdn_buscarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_buscar)
                .addGap(15, 15, 15))
        );
        rdn_buscarLayout.setVerticalGroup(
            rdn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscar)
            .addComponent(jb_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tabla_reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_reportes);

        rdn_imprimir.setBackground(new java.awt.Color(51, 153, 0));
        rdn_imprimir.setRoundBottomLeft(20);
        rdn_imprimir.setRoundBottomRight(20);
        rdn_imprimir.setRoundTopLeft(20);
        rdn_imprimir.setRoundTopRight(20);

        jb_actualizar.setBackground(new java.awt.Color(255, 255, 255));
        jb_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-imprimir-28.png"))); // NOI18N
        jb_actualizar.setText("   IMPRIMIR");
        jb_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout rdn_imprimirLayout = new javax.swing.GroupLayout(rdn_imprimir);
        rdn_imprimir.setLayout(rdn_imprimirLayout);
        rdn_imprimirLayout.setHorizontalGroup(
            rdn_imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdn_imprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );
        rdn_imprimirLayout.setVerticalGroup(
            rdn_imprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdn_imprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rdn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rdn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(394, 394, 394))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(texto_inicio)
                .addGap(17, 17, 17)
                .addComponent(rdn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdn_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jb_actualizar;
    public javax.swing.JLabel jb_buscar;
    public Recursos_Codigo.Redondeado rdn_buscar;
    public Recursos_Codigo.Redondeado rdn_imprimir;
    public javax.swing.JTable tabla_reportes;
    public javax.swing.JLabel texto_inicio;
    public javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
