/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Grupo1;

import Vista.Grupo3.*;

/**
 *
 * @author sitrayas
 */
public class Menu_Campo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prueba_InstanciarMenu
     */
    public Menu_Campo() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_contenedor_menu_acopio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        boton_campo_uno = new Recursos_Codigo.Redondeado();
        jLabel2 = new javax.swing.JLabel();
        boton_campo_dos = new Recursos_Codigo.Redondeado();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        boton_listar_uno = new Recursos_Codigo.Redondeado();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(300, 516));
        setMinimumSize(new java.awt.Dimension(300, 516));
        setPreferredSize(new java.awt.Dimension(300, 516));

        jp_contenedor_menu_acopio.setBackground(new java.awt.Color(204, 204, 204));
        jp_contenedor_menu_acopio.setMaximumSize(new java.awt.Dimension(290, 480));
        jp_contenedor_menu_acopio.setMinimumSize(new java.awt.Dimension(290, 480));
        jp_contenedor_menu_acopio.setName(""); // NOI18N
        jp_contenedor_menu_acopio.setPreferredSize(new java.awt.Dimension(290, 480));
        jp_contenedor_menu_acopio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(270, 48));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/control1.png"))); // NOI18N
        jLabel1.setText("Control");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 248, -1));

        jp_contenedor_menu_acopio.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 40));

        jPanel2.setBackground(new java.awt.Color(112, 39, 1));
        jPanel2.setMaximumSize(new java.awt.Dimension(267, 3));
        jPanel2.setMinimumSize(new java.awt.Dimension(267, 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(267, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jp_contenedor_menu_acopio.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, -1));

        boton_campo_uno.setBackground(new java.awt.Color(204, 204, 204));
        boton_campo_uno.setMaximumSize(new java.awt.Dimension(218, 38));
        boton_campo_uno.setMinimumSize(new java.awt.Dimension(218, 38));
        boton_campo_uno.setPreferredSize(new java.awt.Dimension(218, 38));
        boton_campo_uno.setRoundBottomLeft(30);
        boton_campo_uno.setRoundBottomRight(30);
        boton_campo_uno.setRoundTopLeft(30);
        boton_campo_uno.setRoundTopRight(30);
        boton_campo_uno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setText("Registro bandejas");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_campo_uno.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, -1, -1));

        jp_contenedor_menu_acopio.add(boton_campo_uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        boton_campo_dos.setBackground(new java.awt.Color(204, 204, 204));
        boton_campo_dos.setMaximumSize(new java.awt.Dimension(218, 38));
        boton_campo_dos.setMinimumSize(new java.awt.Dimension(218, 38));
        boton_campo_dos.setPreferredSize(new java.awt.Dimension(218, 38));
        boton_campo_dos.setRoundBottomLeft(30);
        boton_campo_dos.setRoundBottomRight(30);
        boton_campo_dos.setRoundTopLeft(30);
        boton_campo_dos.setRoundTopRight(30);
        boton_campo_dos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Listado bandejas");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_campo_dos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, -1, -1));

        jp_contenedor_menu_acopio.add(boton_campo_dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(270, 48));
        jPanel3.setMinimumSize(new java.awt.Dimension(270, 48));
        jPanel3.setPreferredSize(new java.awt.Dimension(270, 48));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/playlist_32px.png"))); // NOI18N
        jLabel4.setText("Reportes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_contenedor_menu_acopio.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, 40));

        boton_listar_uno.setBackground(new java.awt.Color(204, 204, 204));
        boton_listar_uno.setMaximumSize(new java.awt.Dimension(218, 38));
        boton_listar_uno.setMinimumSize(new java.awt.Dimension(218, 38));
        boton_listar_uno.setPreferredSize(new java.awt.Dimension(218, 38));
        boton_listar_uno.setRoundBottomLeft(30);
        boton_listar_uno.setRoundBottomRight(30);
        boton_listar_uno.setRoundTopLeft(30);
        boton_listar_uno.setRoundTopRight(30);
        boton_listar_uno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setText("Nuevo reporte");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_listar_uno.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, -1, -1));

        jp_contenedor_menu_acopio.add(boton_listar_uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor_menu_acopio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor_menu_acopio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Recursos_Codigo.Redondeado boton_campo_dos;
    public Recursos_Codigo.Redondeado boton_campo_uno;
    public Recursos_Codigo.Redondeado boton_listar_uno;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jp_contenedor_menu_acopio;
    // End of variables declaration//GEN-END:variables
}
