/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Grupo1;

/**
 *
 * @author SITRAYAS-LENOVO
 */
public class Vista_campo_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_campo_1
     */
    public Vista_campo_1() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator34 = new javax.swing.JSeparator();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jSeparator36 = new javax.swing.JSeparator();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jLabel38 = new javax.swing.JLabel();
        jCheckBox58 = new javax.swing.JCheckBox();
        jSeparator37 = new javax.swing.JSeparator();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JSeparator();
        jCheckBox64 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox65 = new javax.swing.JCheckBox();
        jLabel40 = new javax.swing.JLabel();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jCheckBox68 = new javax.swing.JCheckBox();
        jSeparator45 = new javax.swing.JSeparator();
        jCheckBox69 = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        jCheckBox91 = new javax.swing.JCheckBox();
        jCheckBox93 = new javax.swing.JCheckBox();
        jLabel48 = new javax.swing.JLabel();
        jCheckBox95 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jSeparator41 = new javax.swing.JSeparator();
        jCheckBox76 = new javax.swing.JCheckBox();
        jSeparator46 = new javax.swing.JSeparator();
        jCheckBox77 = new javax.swing.JCheckBox();
        jLabel49 = new javax.swing.JLabel();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox96 = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jCheckBox97 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        jSeparator42 = new javax.swing.JSeparator();
        jCheckBox79 = new javax.swing.JCheckBox();
        jCheckBox80 = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        jSeparator43 = new javax.swing.JSeparator();
        jCheckBox81 = new javax.swing.JCheckBox();
        jCheckBox82 = new javax.swing.JCheckBox();
        jLabel54 = new javax.swing.JLabel();
        jCheckBox83 = new javax.swing.JCheckBox();
        jCheckBox98 = new javax.swing.JCheckBox();
        jCheckBox84 = new javax.swing.JCheckBox();
        jCheckBox99 = new javax.swing.JCheckBox();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox101 = new javax.swing.JCheckBox();
        jCheckBox102 = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox85 = new javax.swing.JCheckBox();
        jCheckBox86 = new javax.swing.JCheckBox();
        jLabel45 = new javax.swing.JLabel();
        jCheckBox87 = new javax.swing.JCheckBox();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jSeparator50 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jCheckBox88 = new javax.swing.JCheckBox();
        jCheckBox103 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox89 = new javax.swing.JCheckBox();
        jCheckBox104 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox105 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox106 = new javax.swing.JCheckBox();
        jSeparator30 = new javax.swing.JSeparator();
        jCheckBox107 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox108 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(965, 605));
        setMinimumSize(new java.awt.Dimension(965, 605));
        setPreferredSize(new java.awt.Dimension(965, 605));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("CÓDIGO:");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("TIPO DE CAJAS:");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("PLACA DE VÍNCULO");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("PRODUCTOR:");

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("HORA EVAL:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("VAPOR:");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("SEMANA:");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("FINCA:");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("FECHA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField9)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, 465, -1));
        jPanel2.add(jCheckBox47, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 207, -1, -1));
        jPanel2.add(jCheckBox48, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 71, -1, -1));
        jPanel2.add(jCheckBox49, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel35.setText("Aplicacion de cal P24 Contorno de empacadora");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));
        jPanel2.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, 465, -1));
        jPanel2.add(jCheckBox50, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 343, -1, -1));
        jPanel2.add(jCheckBox51, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 343, -1, -1));

        jLabel36.setText("Cerramiento de empacadora con malla zaran");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 377, -1, -1));
        jPanel2.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 402, 465, -1));
        jPanel2.add(jCheckBox52, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 377, -1, -1));
        jPanel2.add(jCheckBox53, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 377, -1, -1));
        jPanel2.add(jCheckBox54, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 105, -1, -1));
        jPanel2.add(jCheckBox55, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 377, -1, -1));
        jPanel2.add(jCheckBox56, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 105, -1, -1));
        jPanel2.add(jCheckBox57, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 105, -1, -1));

        jLabel38.setText("Colocacion de pediluvios al ingreso empacadora");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, -1, -1));
        jPanel2.add(jCheckBox58, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 207, -1, -1));
        jPanel2.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 465, -1));
        jPanel2.add(jCheckBox59, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 207, -1, -1));
        jPanel2.add(jCheckBox60, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 139, -1, -1));

        jLabel39.setText("Uso rodillos para pegar cartón");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 241, -1, -1));
        jPanel2.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, 465, -1));

        jCheckBox64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox64ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox64, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 35, -1, -1));

        jLabel14.setText("PUNTO DE CONTROL");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 6, -1, -1));

        jLabel15.setText("BUENO");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 6, -1, -1));

        jLabel16.setText("MALO");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 6, -1, -1));
        jPanel2.add(jCheckBox65, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 241, -1, -1));

        jLabel40.setText("REGULAR");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 6, -1, -1));
        jPanel2.add(jCheckBox66, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 241, -1, -1));
        jPanel2.add(jCheckBox67, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 241, -1, -1));

        jLabel41.setText("Bombas con boquillas adecuadas");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 275, -1, -1));
        jPanel2.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 300, 465, -1));

        jLabel47.setText("Cartón sobre pallets");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 241, -1, -1));
        jPanel2.add(jCheckBox68, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 275, -1, -1));
        jPanel2.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 266, 465, -1));
        jPanel2.add(jCheckBox69, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 139, -1, -1));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 62, 465, -1));
        jPanel2.add(jCheckBox91, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 37, -1, -1));
        jPanel2.add(jCheckBox93, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 37, -1, -1));

        jLabel48.setText("Limpi. Hera. (Bandejas, cunas, balanzas, radios)");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 71, -1, -1));
        jPanel2.add(jCheckBox95, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 37, -1, -1));
        jPanel2.add(jCheckBox70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));
        jPanel2.add(jCheckBox71, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 275, -1, -1));
        jPanel2.add(jCheckBox72, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 275, -1, -1));
        jPanel2.add(jCheckBox73, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 139, -1, -1));
        jPanel2.add(jCheckBox74, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 275, -1, -1));
        jPanel2.add(jCheckBox75, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 275, -1, -1));
        jPanel2.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 232, 465, -1));
        jPanel2.add(jCheckBox76, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 210, -1, -1));
        jPanel2.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 96, 465, -1));
        jPanel2.add(jCheckBox77, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 71, -1, -1));

        jLabel49.setText("PUNTO DE CONTROL");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 6, -1, -1));
        jPanel2.add(jCheckBox78, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 71, -1, -1));
        jPanel2.add(jCheckBox96, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 71, -1, -1));

        jLabel50.setText("BUENO");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 6, -1, -1));

        jLabel51.setText("Baños con utencilios de higiene");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 309, -1, -1));

        jLabel52.setText("Ropa adecuada (pantal. largo, camiseta, zapatos)");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 173, -1, -1));
        jPanel2.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 334, 465, -1));
        jPanel2.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 198, 465, 6));

        jLabel53.setText("MALO");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 6, -1, -1));
        jPanel2.add(jCheckBox97, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 241, -1, -1));

        jLabel42.setText("Cunas en buenas condiciones");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 105, -1, -1));
        jPanel2.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 130, 465, -1));
        jPanel2.add(jCheckBox79, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 343, -1, -1));
        jPanel2.add(jCheckBox80, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 343, -1, -1));

        jLabel43.setText("Lavado de racimos con buena presión");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 377, -1, -1));
        jPanel2.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 402, 465, -1));
        jPanel2.add(jCheckBox81, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 377, -1, -1));
        jPanel2.add(jCheckBox82, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 377, -1, -1));

        jLabel54.setText("REGULAR");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(843, 6, -1, -1));
        jPanel2.add(jCheckBox83, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 105, -1, -1));
        jPanel2.add(jCheckBox98, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 241, -1, -1));
        jPanel2.add(jCheckBox84, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 377, -1, -1));
        jPanel2.add(jCheckBox99, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 309, -1, -1));
        jPanel2.add(jCheckBox100, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 309, -1, -1));
        jPanel2.add(jCheckBox101, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 241, -1, -1));
        jPanel2.add(jCheckBox102, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 309, -1, -1));

        jLabel55.setText("Lavado de manos al ingreso de una empacadora");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 275, -1, -1));

        jLabel56.setText("Canateletas de tinas limpias de moho, lama");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 343, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 465, -1));
        jPanel2.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 300, 465, -1));

        jLabel21.setText("Empacadora Pintada (Tinas, paredes, banos)");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, -1, -1));
        jPanel2.add(jCheckBox85, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 105, -1, -1));
        jPanel2.add(jCheckBox86, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 105, -1, -1));

        jLabel45.setText("Personal con equipo de protección completa");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 139, -1, -1));
        jPanel2.add(jCheckBox87, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 210, -1, -1));
        jPanel2.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 164, 465, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 28, 465, -1));

        jLabel46.setText("Agua corrida con buena presión");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 40, -1, -1));
        jPanel2.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 368, 465, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 465, -1));
        jPanel2.add(jCheckBox88, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 210, -1, -1));
        jPanel2.add(jCheckBox103, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 275, -1, -1));
        jPanel2.add(jCheckBox37, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 37, -1, -1));
        jPanel2.add(jCheckBox89, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 139, -1, -1));
        jPanel2.add(jCheckBox104, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 343, -1, -1));
        jPanel2.add(jCheckBox38, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 37, -1, -1));
        jPanel2.add(jCheckBox105, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 139, -1, -1));

        jLabel28.setText("Limpieza de empacadora adecuada");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));
        jPanel2.add(jCheckBox106, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 173, -1, -1));
        jPanel2.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 465, -1));
        jPanel2.add(jCheckBox107, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 173, -1, -1));
        jPanel2.add(jCheckBox39, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 71, -1, -1));
        jPanel2.add(jCheckBox108, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 173, -1, -1));

        jLabel31.setText("Fumigación de corona con agua de bidón");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 309, -1, -1));

        jLabel57.setText("Material de empace ordenado adecuadamente");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 213, -1, -1));

        jLabel32.setText("Uso de clorinador/Bomba de Peroxido");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 173, -1, -1));
        jPanel2.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 334, 465, -1));
        jPanel2.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 198, 465, -1));
        jPanel2.add(jCheckBox40, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 309, -1, -1));
        jPanel2.add(jCheckBox41, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 309, -1, -1));
        jPanel2.add(jCheckBox42, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 309, -1, -1));

        jLabel33.setText("Mesa para evaluar grado y longitud de dedo");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 343, -1, -1));
        jPanel2.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 368, 465, -1));
        jPanel2.add(jCheckBox43, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 343, -1, -1));
        jPanel2.add(jCheckBox44, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 173, -1, -1));
        jPanel2.add(jCheckBox45, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 173, -1, -1));
        jPanel2.add(jCheckBox46, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 173, -1, -1));

        jLabel34.setText("Uso de pegadora de cartón");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 207, -1, -1));

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox64ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox100;
    private javax.swing.JCheckBox jCheckBox101;
    private javax.swing.JCheckBox jCheckBox102;
    private javax.swing.JCheckBox jCheckBox103;
    private javax.swing.JCheckBox jCheckBox104;
    private javax.swing.JCheckBox jCheckBox105;
    private javax.swing.JCheckBox jCheckBox106;
    private javax.swing.JCheckBox jCheckBox107;
    private javax.swing.JCheckBox jCheckBox108;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox80;
    private javax.swing.JCheckBox jCheckBox81;
    private javax.swing.JCheckBox jCheckBox82;
    private javax.swing.JCheckBox jCheckBox83;
    private javax.swing.JCheckBox jCheckBox84;
    private javax.swing.JCheckBox jCheckBox85;
    private javax.swing.JCheckBox jCheckBox86;
    private javax.swing.JCheckBox jCheckBox87;
    private javax.swing.JCheckBox jCheckBox88;
    private javax.swing.JCheckBox jCheckBox89;
    private javax.swing.JCheckBox jCheckBox91;
    private javax.swing.JCheckBox jCheckBox93;
    private javax.swing.JCheckBox jCheckBox95;
    private javax.swing.JCheckBox jCheckBox96;
    private javax.swing.JCheckBox jCheckBox97;
    private javax.swing.JCheckBox jCheckBox98;
    private javax.swing.JCheckBox jCheckBox99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
